const fs = require('fs');
const { exec } = require('child_process');
const prompts = require('prompts');

// Tentacles Interactive Setup Wizard
async function onboardUser() {
  console.log('\n=============================================');
  console.log(' 🦑    Tentacles LMA Configuration Wizard   🦑');
  console.log('=============================================\n');
  console.log('Please provide the following credentials to initialize your ecosystem.\n');

  const questions = [
    {
      type: 'password',
      name: 'LLM_API_KEY',
      message: 'Enter your Primary LLM API Key (e.g. OpenAI/Anthropic):',
      validate: value => value.length > 10 ? true : 'Please enter a valid API Key.'
    },
    {
      type: 'text',
      name: 'TUNNEL_TOKEN',
      message: 'Enter your Tunneling Token (Ngrok / Localtonet) for public agent webhooks:',
    },
    {
      type: 'password',
      name: 'BOT_TOKEN',
      message: 'Enter your Telegram/Discord Bot Token (optional, press Enter to skip):',
      initial: ''
    }
  ];

  const answers = await prompts(questions);

  // If user hits Ctrl+C, answers will be empty
  if (!answers.LLM_API_KEY) {
      console.log('\n❌ Setup cancelled by user.');
      process.exit(1);
  }

  console.log('\n📝 Saving configuration secure vault (.env)...');
  
  const envData = `
# Autogenerated by Tentacles Installer
LLM_API_KEY=${answers.LLM_API_KEY}
TUNNEL_TOKEN=${answers.TUNNEL_TOKEN}
BOT_TOKEN=${answers.BOT_TOKEN || 'none'}
NODE_ENV=production
  `.trim() + '\n';

  fs.writeFileSync('.env', envData, { encoding: 'utf8' });
  console.log('✅ Configuration securely saved.\n');

  console.log('🚀 Booting up Tentacles Container Sandbox (docker compose up -d)...');
  console.log('   Please wait, this may take a minute...\n');

  // Trigger daemonized docker compose
  const dockerProcess = exec('docker compose up -d');

  dockerProcess.stdout.on('data', data => process.stdout.write(data));
  dockerProcess.stderr.on('data', data => process.stderr.write(data));

  dockerProcess.on('close', (code) => {
    if (code === 0) {
      console.log('\n=============================================');
      console.log(' 🎉 TENTACLES IS LIVE & ORCHESTRATING 🎉');
      console.log('=============================================');
      console.log(' Dashboard: http://localhost:3000');
      console.log(' To view raw logs, run: docker compose logs -f');
      console.log('=============================================\n');
    } else {
      console.log('\n❌ Failed to build or start Docker containers. Exit code:', code);
    }
  });
}

onboardUser().catch(console.error);
